// Base de datos de artistas organizados por género
// Archivo separado para facilitar mantenimiento y actualizaciones

 const artistsByGenre = {
  rock: ["The Beatles","The Rolling Stones","Led Zeppelin","Pink Floyd","Queen","The Who","AC/DC","Guns N' Roses","Aerosmith","U2","The Doors","Deep Purple","Bon Jovi","Nirvana","Pearl Jam","Radiohead","Coldplay","The Police","Dire Straits","Red Hot Chili Peppers"],
  pop: ["Michael Jackson","Madonna","Prince","Whitney Houston","Mariah Carey","Taylor Swift","Dua Lipa","Ariana Grande","Katy Perry","Lady Gaga","Britney Spears","Christina Aguilera","Ed Sheeran","Bruno Mars","Justin Bieber","Selena Gomez","Shawn Mendes","Billie Eilish","Harry Styles","Olivia Rodrigo"],
  jazz: ["Miles Davis","John Coltrane","Louis Armstrong","Duke Ellington","Ella Fitzgerald","Charlie Parker","Billie Holiday","Thelonious Monk","Herbie Hancock","Chet Baker","Sarah Vaughan","Sonny Rollins","Charles Mingus","Dizzy Gillespie","Stan Getz","Wynton Marsalis","Ornette Coleman","Chick Corea","Pat Metheny","Esperanza Spalding"],
  blues: ["B.B. King","Muddy Waters","Robert Johnson","Stevie Ray Vaughan","John Lee Hooker","Buddy Guy","Albert King","Howlin' Wolf","Etta James","Elmore James","Freddie King","Junior Wells","Otis Rush","Son House","T-Bone Walker","Willie Dixon","Big Mama Thornton","Koko Taylor","Johnny Winter","Bonnie Raitt"],
  soul: ["Aretha Franklin","Otis Redding","Marvin Gaye","Stevie Wonder","Ray Charles","Sam Cooke","Smokey Robinson","Al Green","Curtis Mayfield","Gladys Knight","The Temptations","Diana Ross","Tina Turner","James Brown","Isaac Hayes","Barry White","Solomon Burke","Patti LaBelle","Donny Hathaway","Erykah Badu"],
  funk: ["James Brown","Parliament-Funkadelic","Prince","Sly & The Family Stone","Rick James","Earth, Wind & Fire","Kool & The Gang","Tower of Power","George Clinton","Bootsy Collins","The Meters","Chic","Cameo","The Gap Band","Ohio Players","Larry Graham","Average White Band","War","Zapp","Shuggie Otis"],
  disco: ["Bee Gees","Donna Summer","Gloria Gaynor","Chic","KC and the Sunshine Band","Village People","Diana Ross","Barry White","Sylvester","The Trammps","ABBA","Sister Sledge","Boney M.","The Jacksons","Hot Chocolate","Amii Stewart","Evelyn 'Champagne' King","Tavares","Patrick Hernandez","The Emotions"],
  reggae: ["Bob Marley","Peter Tosh","Jimmy Cliff","Burning Spear","Toots & The Maytals","Ziggy Marley","Damian Marley","Gregory Isaacs","Steel Pulse","Black Uhuru","Dennis Brown","Buju Banton","Shabba Ranks","Sean Paul","Chronixx","Protoje","Alborosie","Capleton","Yellowman","Sizzla"],
  salsa: ["Celia Cruz","Héctor Lavoe","Rubén Blades","Marc Anthony","Willie Colón","Oscar D’León","Tito Puente","Johnny Pacheco","Ismael Rivera","Ray Barretto","Cheo Feliciano","Eddie Palmieri","Larry Harlow","Pete 'El Conde' Rodríguez","Adalberto Santiago","Charlie Palmieri","Frankie Ruiz","La India","Víctor Manuelle","Gilberto Santa Rosa"],
  merengue: ["Juan Luis Guerra","Johnny Ventura","Sergio Vargas","Milly Quezada","Eddy Herrera","Wilfrido Vargas","Toño Rosario","Elvis Crespo","Omega","Jandy Ventura","Hermanos Rosario","Bonny Cepeda","Kinito Méndez","Rubby Pérez","Rikarena","Fernando Villalona","Miriam Cruz","Pochy Familia","Krisspy","Los Ilegales"],
  bachata: ["Romeo Santos","Aventura","Prince Royce","Juan Luis Guerra","Zacarías Ferreira","Joe Veras","Antony Santos","Frank Reyes","Luis Vargas","Andy Andy","Yoskar Sarante","El Torito (Héctor Acosta)","Kiko Rodríguez","Monchy & Alexandra","Teodoro Reyes","Raulín Rodríguez","Ramón Cordero","Leonardo Paniagua","Blas Durán","Grupo Extra"],
  cumbia: ["Los Ángeles Azules","La Sonora Dinamita","Los Palmeras","Ráfaga","Gilda","La Nueva Luna","Los Charros","Karicia","Los Mirlos","Lucho Bermúdez","Pastor López","Antonio Ríos","Selva Negra","Agapornis","Mar Azul","Los Totora","Leo Mattioli","Rodrigo Tapari","La Delio Valdez","Damas Gratis"],
  cumbiaVillera: ["Damas Gratis","Pibes Chorros","Yerba Brava","Mala Fama","Meta Guacha","Amar Azul","Supermerk2","Los Gedes","Flor de Piedra","La Base","La Liga","El Empuje","La Champions Liga","Los del Fuego","Agrupación Marilyn","Altos Cumbieros","Los Nota Lokos","El Polaco","Sebastián Mendoza","El Original"],
  tango: ["Carlos Gardel","Astor Piazzolla","Aníbal Troilo","Osvaldo Pugliese","Juan D’Arienzo","Roberto Goyeneche","Edmundo Rivero","Horacio Salgán","Mercedes Simone","Francisco Canaro","Nelly Omar","Hugo del Carril","Adolfo Carabelli","Enrique Santos Discépolo","Julio Sosa","Adriana Varela","Susana Rinaldi","Jorge Sobral","Leopoldo Federico","Orquesta Típica Fernández Fierro"],
  flamenco: ["Paco de Lucía","Camarón de la Isla","Vicente Amigo","Tomatito","Niña Pastori","Estrella Morente","Pepe Habichuela","José Mercé","Manolo Sanlúcar","Diego El Cigala","Fosforito","Remedios Amaya","La Paquera de Jerez","Duquende","El Lebrijano","Rafael Riqueni","Antonio Mairena","Enrique Morente","José Menese","Pitingo"],
  bolero: ["Luis Miguel","Trío Los Panchos","Armando Manzanero","Antonio Machín","José Feliciano","Lucho Gatica","Julio Jaramillo","Los Tres Reyes","Daniel Santos","Olga Guillot","Marco Antonio Muñiz","Bienvenido Granda","Alfredo Sadel","Alberto Cortez","Pablo Milanés","Vicente Garrido","Chavela Vargas","Eydie Gormé","Bobby Capó","Ibrahim Ferrer"],
  mariachi: ["Vicente Fernández","José Alfredo Jiménez","Pedro Infante","Alejandro Fernández","Aida Cuevas","Lucha Villa","Javier Solís","Flor Silvestre","Antonio Aguilar","Pepe Aguilar","Amalia Mendoza","Juan Valentín","Marco Antonio Solís","Ana Gabriel","Mariachi Vargas de Tecalitlán","Mariachi Sol de México","Mariachi Cobre","Christian Nodal","Lucero","Lupita D’Alessio"],
  corrido: ["Los Tigres del Norte","Chalino Sánchez","Gerardo Ortiz","El Komander","Los Tucanes de Tijuana","Alfredo Olivas","Los Huracanes del Norte","Los Alegres de Terán","Valentín Elizalde","Larry Hernández","El Fantasma","Régulo Caro","Adriel Favela","Calibre 50","Pancho Barraza","Saúl 'El Jaguar'","Remmy Valenzuela","Christian Nodal","Virlan García","Fuerza Regida"],
  norteño: ["Ramón Ayala","Los Tucanes de Tijuana","Intocable","Los Huracanes del Norte","Pesado","Bronco","Los Rieleros del Norte","La Maquinaria Norteña","Los Invasores de NL","Los Cadetes de Linares","Los Traileros del Norte","Fito Olivares","La Fiera de Ojinaga","Los Tremendos Gavilanes","Cardenales de NL","Grupo Frontera","Los Temerarios","Duelo","Tigres del Norte (temprano)","Conjunto Primavera"],
  ranchera: ["Javier Solís","Lucha Villa","Pedro Infante","Pepe Aguilar","Amalia Mendoza","Antonio Aguilar","Vicente Fernández","Chavela Vargas","José Alfredo Jiménez","Cuco Sánchez","Aida Cuevas","Jorge Negrete","Lola Beltrán","Ana Gabriel","Alejandro Fernández","Pedro Fernández","Lucero","Luis Miguel","Marco Antonio Solís","Juan Gabriel"],
  gospel: ["Mahalia Jackson","Kirk Franklin","Aretha Franklin","Sister Rosetta Tharpe","Yolanda Adams","Donnie McClurkin","CeCe Winans","Mary Mary","Tasha Cobbs Leonard","Richard Smallwood","Smokie Norful","Shirley Caesar","James Cleveland","Andraé Crouch","Mavis Staples","Travis Greene","Israel Houghton","Fred Hammond","The Clark Sisters","Tamela Mann"],
  country: ["Johnny Cash","Dolly Parton","Garth Brooks","Shania Twain","Carrie Underwood","Willie Nelson","Luke Bryan","Kacey Musgraves","Blake Shelton","George Strait","Reba McEntire","Hank Williams","Loretta Lynn","Kenny Rogers","Alan Jackson","Tim McGraw","Faith Hill","Keith Urban","Miranda Lambert","Chris Stapleton"],
  folk: ["Bob Dylan","Joan Baez","Simon & Garfunkel","Woody Guthrie","Neil Young","Cat Stevens","Joni Mitchell","Leonard Cohen","Peter, Paul and Mary","Nick Drake","Fairport Convention","The Byrds","Crosby, Stills & Nash","Donovan","James Taylor","Gordon Lightfoot","Odetta","Sufjan Stevens","Fleet Foxes","Iron & Wine"],
  bluegrass: ["Bill Monroe","Earl Scruggs","Ricky Skaggs","Alison Krauss","Flatt & Scruggs","Del McCoury","Tony Rice","Sam Bush","The Stanley Brothers","Doc Watson","Béla Fleck","JD Crowe","Rhonda Vincent","Chris Thile","Punch Brothers","Doyle Lawson","Blue Highway","Mountain Heart","Larry Sparks","Dailey & Vincent"],
  heavyMetal: ["Iron Maiden","Judas Priest","Black Sabbath","Helloween","Manowar","Saxon","Accept","Dio","Motörhead","Scorpions","Pantera","Metal Church","Yngwie Malmsteen","Stratovarius","Gamma Ray","Iced Earth","Primal Fear","DragonForce","Angra","Nightwish"],
  thrashMetal: ["Metallica","Slayer","Megadeth","Anthrax","Exodus","Testament","Overkill","Sepultura","Kreator","Sodom","Destruction","Vio-Lence","Havok","Heathen","Annihilator","Death Angel","Forbidden","Municipal Waste","Tankard","Sacred Reich"],
  industrialMetal: ["Rammstein","Nine Inch Nails","Ministry","Static-X","Fear Factory","KMFDM","Marilyn Manson","Rob Zombie","Godflesh","Dope","Orgy","Powerman 5000","Pitchshifter","Prong","Skinny Puppy","Oomph!","Stabbing Westward","Celldweller","Filter","Gravity Kills"],
  blackMetal: ["Mayhem","Burzum","Emperor","Darkthrone","Immortal","Gorgoroth","Enslaved","Satyricon","Bathory","Carpathian Forest","Marduk","Dissection","1349","Watain","Dimmu Borgir","Naglfar","Taake","Ulver","Borknagar","Beherit"],
  deathMetal: ["Cannibal Corpse","Death","Morbid Angel","Obituary","Deicide","Behemoth","Entombed","Nile","Bolt Thrower","Carcass","At the Gates","Arch Enemy","Amon Amarth","Katatonia","Hypocrisy","Malevolent Creation","Suffocation","Dying Fetus","Gorguts","Bloodbath"],
  punk: ["Ramones","Sex Pistols","The Clash","Dead Kennedys","Misfits","Buzzcocks","The Damned","Black Flag","Bad Religion","Descendents","NOFX","Rancid","Green Day","The Offspring","Pennywise","Anti-Flag","Dropkick Murphys","The Exploited","Lagwagon","Fugazi"],
  hardcorePunk: ["Black Flag","Minor Threat","Bad Brains","Fugazi","Circle Jerks","Youth of Today","Gorilla Biscuits","Agnostic Front","Sick of It All","Cro-Mags","Snapcase","Refused","Converge","Poison Idea","7 Seconds","D.R.I.","Uniform Choice","Chain of Strength","Madball","Earth Crisis"],
  grunge: ["Nirvana","Pearl Jam","Soundgarden","Alice in Chains","Stone Temple Pilots","Mudhoney","Screaming Trees","Temple of the Dog","Mother Love Bone","Bush","Silverchair","Smashing Pumpkins","Hole","L7","Babes in Toyland","Melvins","Live","Collective Soul","Everclear","Soundgarden (Chris Cornell)"],
  alternativeRock: ["Radiohead","Red Hot Chili Peppers","Arctic Monkeys","Coldplay","The Killers","Muse","Oasis","Blur","The Smashing Pumpkins","R.E.M.","Beck","Placebo","Interpol","Kasabian","Franz Ferdinand","Foo Fighters","Queens of the Stone Age","The Cure","Nick Cave & The Bad Seeds","Florence + The Machine"],
  progressiveRock: ["Pink Floyd","Genesis","Yes","King Crimson","Rush","Dream Theater","ELP","Jethro Tull","Camel","Marillion","Porcupine Tree","Gentle Giant","Kansas","Transatlantic","Arena","IQ","Asia","Opeth","Neal Morse Band","Steven Wilson"],
  indieRock: ["The Strokes","Arctic Monkeys","Vampire Weekend","Franz Ferdinand","Tame Impala","Interpol","The White Stripes","Yeah Yeah Yeahs","MGMT","Modest Mouse","The Libertines","Arcade Fire","Phoenix","Two Door Cinema Club","Bloc Party","Foals","The Shins","The Kooks","Death Cab for Cutie","War on Drugs"],
  rb: ["Beyoncé","Rihanna","Usher","Alicia Keys","The Weeknd","Chris Brown","Mary J. Blige","SZA","Frank Ocean","Miguel","Ne-Yo","Trey Songz","Ciara","Brandy","Monica","Toni Braxton","Boyz II Men","Tyrese","Janelle Monáe","H.E.R."],
  hiphop: ["Kendrick Lamar","Drake","J. Cole","Jay-Z","Kanye West","Travis Scott","Nicki Minaj","Cardi B","Tyler, The Creator","A$AP Rocky","Run-DMC","LL Cool J","Rakim","Ice Cube","Public Enemy","Outkast","N.W.A.","Lil Wayne","Nas","50 Cent"],
  rap: ["Eminem","Nas","Tupac","The Notorious B.I.G.","Lil Wayne","Ice Cube","Run-DMC","Rakim","Snoop Dogg","Jay-Z","Big L","DMX","J. Cole","Kendrick Lamar","Busta Rhymes","Big Pun","KRS-One","Tech N9ne","Killer Mike","Mos Def"],
  trap: ["Bad Bunny","Anuel AA","Travis Scott","Future","Migos","Lil Baby","21 Savage","Young Thug","Playboi Carti","Lil Uzi Vert","Offset","Kodak Black","Roddy Ricch","DaBaby","Don Toliver","Ski Mask the Slump God","Gunna","NAV","Trippie Redd","YBN Nahmir"],
  reggaeton: ["Daddy Yankee","J Balvin","Karol G","Ozuna","Nicky Jam","Maluma","Feid","Rauw Alejandro","Anuel AA","Wisin & Yandel","Chencho Corleone","Ivy Queen","Don Omar","Farruko","Arcángel","De La Ghetto","Sech","Bryant Myers","Lunay","Tego Calderón"],
  dancehall: ["Sean Paul","Shabba Ranks","Beenie Man","Buju Banton","Vybz Kartel","Bounty Killer","Elephant Man","Gyptian","Konshens","Popcaan","Mr. Vegas","Spice","Aidonia","Agent Sasco","T.O.K.","Cham","Mavado","Serani","Koffee","Alkaline"],
  kpop: ["BTS","BLACKPINK","EXO","TWICE","Red Velvet","Stray Kids","SEVENTEEN","NCT 127","ITZY","AESPA","GOT7","TXT","BigBang","Girls' Generation","Super Junior","2NE1","SHINee","LE SSERAFIM","NewJeans","IVE"],
  jpop: ["Hikaru Utada","Perfume","Arashi","Kyary Pamyu Pamyu","Babymetal","Namie Amuro","Ayumi Hamasaki","Morning Musume","X Japan","B'z","L'Arc~en~Ciel","AKB48","King & Prince","Nogizaka46","Gen Hoshino","Ken Hirai","One Ok Rock","RADWIMPS","Mr. Children","SEKAI NO OWARI"],
  afrobeat: ["Fela Kuti","Tony Allen","Burna Boy","Wizkid","Davido","Seun Kuti","Femi Kuti","Mr Eazi","Yemi Alade","Tiwa Savage","Rema","Tems","CKay","Fireboy DML","Olamide","P-Square","Kizz Daniel","Ayra Starr","Tekno","Joeboy"],
  highlife: ["E.T. Mensah","Osibisa","Chief Stephen Osita Osadebe","Victor Olaiya","Nana Ampadu","King Sunny Adé (jujú/highlife fusión)","Félá Ransome-Kuti (temprano)","Daddy Lumba","Amakye Dede","Gyedu-Blay Ambolley","Prince Nico Mbarga","Pat Thomas","Fatawu Amadu","Rex Lawson","A.B. Crentsil","Alex Konadu","Sir Victor Uwaifo","Oliver De Coque","Flavour N'abania","Chief Shina Peters"],
  techno: ["Carl Cox","Jeff Mills","Richie Hawtin","Adam Beyer","Charlotte de Witte","Amelie Lens","Sven Väth","Laurent Garnier","Nina Kraviz","Derrick May","Juan Atkins","Kevin Saunderson","Len Faki","Ben Klock","Marcel Dettmann","Dave Clarke","Green Velvet","Dubfire","Chris Liebing","Joseph Capriati"],
  house: ["Frankie Knuckles","David Guetta","Calvin Harris","Avicii","Swedish House Mafia","Daft Punk","Deadmau5","Eric Prydz","Kaskade","Disclosure","Armand van Helden","Todd Terry","Masters at Work","Cassius","Bob Sinclar","Robin S.","Roger Sanchez","MK (Marc Kinchen)","Duke Dumont","Claptone"],
  trance: ["Armin van Buuren","Paul van Dyk","Tiesto","Ferry Corsten","Above & Beyond","ATB","Dash Berlin","Aly & Fila","Cosmic Gate","Paul Oakenfold","BT","Gareth Emery","Markus Schulz","Giuseppe Ottaviani","Andrew Rayel","MaRLo","Orjan Nilsen","Lange","Johan Gielen","Sander van Doorn"],
  drumAndBass: ["Goldie","Roni Size","Andy C","Noisia","Pendulum","High Contrast","LTJ Bukem","Sub Focus","Netsky","Chase & Status","DJ Hype","Bad Company UK","Calyx & Teebee","Logistics","Danny Byrd","Dimension","Friction","Alix Perez","Break","S.P.Y"],
  dubstep: ["Skrillex","Rusko","Excision","Zomboy","Flux Pavilion","Benga","Skream","Doctor P","Knife Party","Virtual Riot","Datsik","Nero","Zeds Dead","Bassnectar","Eptic","Barely Alive","Trampa","Space Laces","Downlink","Snails"],
  ska: ["The Specials","Madness","Toots & The Maytals","Desmond Dekker","The Skatalites","The Selecter","Bad Manners","Hepcat","The Toasters","Reel Big Fish","Less Than Jake","The Mighty Mighty Bosstones","The Slackers","Operation Ivy","Streetlight Manifesto","Fishbone","Prince Buster","Laurel Aitken","Alton Ellis","Eastern Standard Time"],
  opera: ["Luciano Pavarotti","Maria Callas","Plácido Domingo","Montserrat Caballé","Andrea Bocelli","Renée Fleming","Jonas Kaufmann","Anna Netrebko","José Carreras","Cecilia Bartoli","Kiri Te Kanawa","Dmitri Hvorostovsky","Bryn Terfel","Jessye Norman","Joan Sutherland","Renata Tebaldi","Franco Corelli","Nicolai Gedda","Elīna Garanča","Piotr Beczała"],
  balada: ["José José","Rocío Dúrcal","Camilo Sesto","Juan Gabriel","Cristian Castro","Luis Fonsi","Laura Pausini","Alejandro Sanz","Ana Gabriel","Ricardo Montaner","Vicente Fernández (baladas)","Yuri","Mijares","Chayanne","Emmanuel","Sandro","Myriam Hernández","Pablo Alborán","David Bisbal","Carlos Rivera"]
};



// Géneros adicionales y búsquedas complementarias
const genericQueries = [
  { query: "reggaeton 2024", maxResults: 15, genre: "Reggaeton" },
  { query: "pop hits 2024", maxResults: 15, genre: "Pop" },
  { query: "rock classics", maxResults: 12, genre: "Rock" },
  { query: "hip hop 2024", maxResults: 12, genre: "Hip Hop" },
  { query: "electronic music 2024", maxResults: 10, genre: "Electronic" },
  { query: "latin hits 2024", maxResults: 12, genre: "Latin" },
  { query: "alternative rock 2024", maxResults: 10, genre: "Alternative" },
  { query: "r&b hits 2024", maxResults: 10, genre: "R&B" },
  { query: "viral songs 2024", maxResults: 15, genre: "Viral" },
  { query: "música latina", maxResults: 12, genre: "Latin" },
  { query: "country hits 2024", maxResults: 10, genre: "Country" },
  { query: "indie music 2024", maxResults: 10, genre: "Indie" },
  { query: "top global hits", maxResults: 20, genre: "Global" },
  { query: "trending music 2024", maxResults: 15, genre: "Trending" },
  { query: "jazz classics", maxResults: 12, genre: "Jazz" },
  { query: "soul music playlist", maxResults: 10, genre: "Soul" },
  { query: "funk greatest hits", maxResults: 10, genre: "Funk" },
  { query: "disco 80s hits", maxResults: 10, genre: "Disco" },
  { query: "reggae best songs", maxResults: 12, genre: "Reggae" },
  { query: "salsa clasicos", maxResults: 12, genre: "Salsa" },
  { query: "merengue clasicos", maxResults: 12, genre: "Merengue" },
  { query: "bachata romantica", maxResults: 12, genre: "Bachata" },
  { query: "cumbia villera hits", maxResults: 12, genre: "Cumbia Villera" },
  { query: "tango argentino", maxResults: 10, genre: "Tango" },
  { query: "flamenco guitarra", maxResults: 10, genre: "Flamenco" },
  { query: "boleros romanticos", maxResults: 12, genre: "Bolero" },
  { query: "mariachi clasicos", maxResults: 10, genre: "Mariachi" },
  { query: "corridos tumbados", maxResults: 12, genre: "Corrido" },
  { query: "norteño music", maxResults: 10, genre: "Norteño" },
  { query: "rancheras clasicas", maxResults: 10, genre: "Ranchera" },
  { query: "gospel music worship", maxResults: 10, genre: "Gospel" },
  { query: "bluegrass classics", maxResults: 10, genre: "Bluegrass" },
  { query: "heavy metal classics", maxResults: 12, genre: "Heavy Metal" },
  { query: "thrash metal live", maxResults: 12, genre: "Thrash Metal" },
  { query: "black metal playlist", maxResults: 10, genre: "Black Metal" },
  { query: "death metal classics", maxResults: 10, genre: "Death Metal" },
  { query: "punk rock 90s", maxResults: 12, genre: "Punk" },
  { query: "hardcore punk", maxResults: 10, genre: "Hardcore Punk" },
  { query: "grunge 90s", maxResults: 12, genre: "Grunge" },
  { query: "progressive rock live", maxResults: 10, genre: "Progressive Rock" },
  { query: "indie rock hits", maxResults: 12, genre: "Indie Rock" },
  { query: "trap hits 2024", maxResults: 12, genre: "Trap" },
  { query: "dancehall 2024", maxResults: 12, genre: "Dancehall" },
  { query: "kpop hits 2024", maxResults: 12, genre: "K-Pop" },
  { query: "jpop hits 2024", maxResults: 12, genre: "J-Pop" },
  { query: "afrobeat hits 2024", maxResults: 12, genre: "Afrobeat" },
  { query: "techno live set", maxResults: 12, genre: "Techno" },
  { query: "house music 2024", maxResults: 12, genre: "House" },
  { query: "trance anthems", maxResults: 12, genre: "Trance" },
  { query: "drum and bass mix", maxResults: 12, genre: "Drum and Bass" },
  { query: "dubstep drops", maxResults: 12, genre: "Dubstep" },
  { query: "ska classics", maxResults: 10, genre: "Ska" },
  { query: "opera arias", maxResults: 10, genre: "Opera" },
  { query: "baladas romanticas", maxResults: 12, genre: "Balada" }
];

module.exports = {
  artistsByGenre,
  genericQueries
};